import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import AdminLayout from "../../layouts/AdminLayout";
import ProtectedRoute from "../../components/user/ProtectedRoute";
import emailLogApi from "../../api/emailLogApi";
import Loader from "../../components/common/Loader";
import EmptyState from "../../components/common/EmptyState";

function AdminEmailLogsPage() {
  const { t, i18n } = useTranslation();

  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    const loadLogs = async () => {
      try {
        const response = await emailLogApi.getAll();
        setLogs(response.data || []);
      } catch (error) {
        console.error("Failed to load email logs:", error);
      } finally {
        setLoading(false);
      }
    };

    loadLogs();
  }, []);

  const filteredLogs = useMemo(() => {
    const keyword = searchTerm.trim().toLowerCase();

    if (!keyword) return logs;

    return logs.filter((log) => {
      const subject = log.subject?.toLowerCase() || "";
      const toEmail = log.toEmail?.toLowerCase() || "";
      const body = log.body?.toLowerCase() || "";
      const type = log.type?.toLowerCase() || "";

      return (
        subject.includes(keyword) ||
        toEmail.includes(keyword) ||
        body.includes(keyword) ||
        type.includes(keyword)
      );
    });
  }, [logs, searchTerm]);

  const handleExport = async () => {
    try {
      setExporting(true);

      const response = await emailLogApi.exportCsv();
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement("a");

      link.href = url;
      link.setAttribute("download", "email-logs.csv");

      document.body.appendChild(link);
      link.click();
      link.remove();

      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Failed to export email logs:", error);
    } finally {
      setExporting(false);
    }
  };

  return (
    <ProtectedRoute adminOnly>
      <AdminLayout>
        <section className="page-shell admin-email-page">
          <div className="container">
            <div className="admin-email-hero card">
              <div>
                <span className="admin-email-eyebrow">
                  {t("admin.notificationCenter", "Notification Center")}
                </span>

                <h1 className="page-title">
                  {t("admin.emailLogsTitle", "Email Logs")}
                </h1>

                <p className="page-subtitle">
                  {t(
                    "admin.emailLogsSubtitle",
                    "Mock email notifications generated by the system.",
                  )}
                </p>
              </div>

              <button
                className="btn btn-primary"
                onClick={handleExport}
                disabled={exporting || logs.length === 0}
              >
                {exporting
                  ? t("common.exporting", "Exporting...")
                  : t("admin.exportCsv", "Export CSV")}
              </button>
            </div>

            <div className="admin-email-stats-grid">
              <div className="card admin-email-stat">
                <span>{t("admin.totalLogs", "Total Logs")}</span>
                <strong>{logs.length}</strong>
              </div>

              <div className="card admin-email-stat">
                <span>{t("admin.visibleLogs", "Visible Logs")}</span>
                <strong>{filteredLogs.length}</strong>
              </div>

              <div className="card admin-email-stat">
                <span>{t("admin.latestLog", "Latest Log")}</span>
                <strong>
                  {logs[0]?.sentAt
                    ? new Date(logs[0].sentAt).toLocaleDateString(i18n.language)
                    : "-"}
                </strong>
              </div>
            </div>

            <div className="card admin-email-toolbar">
              <div>
                <label>{t("admin.searchEmailLogs", "Search Email Logs")}</label>
                <input
                  className="input-field"
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder={t(
                    "admin.searchEmailLogsPlaceholder",
                    "Search by subject, email, body, or type...",
                  )}
                />
              </div>
            </div>

            {loading ? (
              <Loader
                text={t("admin.loadingEmailLogs", "Loading email logs...")}
              />
            ) : filteredLogs.length === 0 ? (
              <EmptyState
                title={t("admin.noEmailLogs", "No email logs")}
                description={t(
                  "admin.noEmailLogsDesc",
                  "There are no email log records yet.",
                )}
              />
            ) : (
              <div className="admin-email-log-list">
                {filteredLogs.map((log) => (
                  <article key={log.id} className="card admin-email-log-card">
                    <div className="admin-email-log-top">
                      <div className="admin-email-icon">✉</div>

                      <div>
                        <h3>{log.subject || "No subject"}</h3>

                        <p className="muted">
                          {t("admin.to", "To")}:{" "}
                          <strong>{log.toEmail || "N/A"}</strong>
                        </p>
                      </div>

                      <span className="admin-email-type">
                        {log.type || "Mock"}
                      </span>
                    </div>

                    <p className="admin-email-body">
                      {log.body || t("admin.noEmailBody", "No email body.")}
                    </p>

                    <div className="admin-email-log-footer">
                      <span>
                        {log.sentAt
                          ? new Date(log.sentAt).toLocaleString(i18n.language)
                          : "N/A"}
                      </span>
                    </div>
                  </article>
                ))}
              </div>
            )}
          </div>
        </section>
      </AdminLayout>
    </ProtectedRoute>
  );
}

export default AdminEmailLogsPage;
