import { useEffect, useState } from "react";
import AdminLayout from "../../layouts/AdminLayout";
import ProtectedRoute from "../../components/user/ProtectedRoute";
import emailLogApi from "../../api/emailLogApi";
import Loader from "../../components/common/Loader";
import EmptyState from "../../components/common/EmptyState";

function AdminEmailLogsPage() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadLogs = async () => {
      try {
        const response = await emailLogApi.getAll();
        setLogs(response.data || []);
      } finally {
        setLoading(false);
      }
    };

    loadLogs();
  }, []);

  const handleExport = async () => {
    const response = await emailLogApi.exportCsv();
    const url = window.URL.createObjectURL(new Blob([response.data]));
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "email-logs.csv");
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  return (
    <ProtectedRoute adminOnly>
      <AdminLayout>
        <section className="page-shell">
          <div className="container">
            <div className="page-title-row">
              <div>
                <h1 className="page-title">Email Logs</h1>
                <p className="page-subtitle">
                  Mock email notifications generated by the system.
                </p>
              </div>
              <button className="btn btn-outline" onClick={handleExport}>
                Export CSV
              </button>
            </div>

            {loading ? (
              <Loader text="Loading email logs..." />
            ) : logs.length === 0 ? (
              <EmptyState
                title="No email logs"
                description="There are no email log records yet."
              />
            ) : (
              <div className="email-log-list">
                {logs.map((log) => (
                  <div key={log.id} className="card email-log-card">
                    <h3>{log.subject}</h3>
                    <p className="muted">To: {log.toEmail}</p>
                    <p>{log.body}</p>
                    <small className="muted">
                      {new Date(log.sentAt).toLocaleString()}
                    </small>
                  </div>
                ))}
              </div>
            )}
          </div>
        </section>
      </AdminLayout>
    </ProtectedRoute>
  );
}

export default AdminEmailLogsPage;
